// Protocol Buffer definitions for Oracle Stream protocol
// Defines message types for price feeder ↔ TMKMS communication

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: privval/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to sign price feed data
type SignPriceFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique request identifier for correlation
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Raw price feed data to be signed
	RawData []byte `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (x *SignPriceFeedRequest) Reset() {
	*x = SignPriceFeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignPriceFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignPriceFeedRequest) ProtoMessage() {}

func (x *SignPriceFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignPriceFeedRequest.ProtoReflect.Descriptor instead.
func (*SignPriceFeedRequest) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *SignPriceFeedRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SignPriceFeedRequest) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

// Response containing the signature
type SignPriceFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the original request
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Cryptographic signature of the raw data
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignPriceFeedResponse) Reset() {
	*x = SignPriceFeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignPriceFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignPriceFeedResponse) ProtoMessage() {}

func (x *SignPriceFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignPriceFeedResponse.ProtoReflect.Descriptor instead.
func (*SignPriceFeedResponse) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *SignPriceFeedResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *SignPriceFeedResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Request for validator's public key
type GetPubKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique request identifier for correlation
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPubKeyRequest) Reset() {
	*x = GetPubKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPubKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPubKeyRequest) ProtoMessage() {}

func (x *GetPubKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPubKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPubKeyRequest) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *GetPubKeyRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response containing the public key
type GetPubKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the original request
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Validator's public key
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *GetPubKeyResponse) Reset() {
	*x = GetPubKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPubKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPubKeyResponse) ProtoMessage() {}

func (x *GetPubKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPubKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPubKeyResponse) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *GetPubKeyResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GetPubKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// Connection health monitoring messages
type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{4}
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{5}
}

// Main message container for the stream
type OracleStreamMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Union field for different message types
	//
	// Types that are assignable to Sum:
	//
	//	*OracleStreamMessage_SignPriceFeedRequest
	//	*OracleStreamMessage_SignPriceFeedResponse
	//	*OracleStreamMessage_GetPubKeyRequest
	//	*OracleStreamMessage_GetPubKeyResponse
	//	*OracleStreamMessage_Ping
	//	*OracleStreamMessage_Pong
	Sum isOracleStreamMessage_Sum `protobuf_oneof:"sum"`
}

func (x *OracleStreamMessage) Reset() {
	*x = OracleStreamMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OracleStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleStreamMessage) ProtoMessage() {}

func (x *OracleStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleStreamMessage.ProtoReflect.Descriptor instead.
func (*OracleStreamMessage) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{6}
}

func (m *OracleStreamMessage) GetSum() isOracleStreamMessage_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (x *OracleStreamMessage) GetSignPriceFeedRequest() *SignPriceFeedRequest {
	if x, ok := x.GetSum().(*OracleStreamMessage_SignPriceFeedRequest); ok {
		return x.SignPriceFeedRequest
	}
	return nil
}

func (x *OracleStreamMessage) GetSignPriceFeedResponse() *SignPriceFeedResponse {
	if x, ok := x.GetSum().(*OracleStreamMessage_SignPriceFeedResponse); ok {
		return x.SignPriceFeedResponse
	}
	return nil
}

func (x *OracleStreamMessage) GetGetPubKeyRequest() *GetPubKeyRequest {
	if x, ok := x.GetSum().(*OracleStreamMessage_GetPubKeyRequest); ok {
		return x.GetPubKeyRequest
	}
	return nil
}

func (x *OracleStreamMessage) GetGetPubKeyResponse() *GetPubKeyResponse {
	if x, ok := x.GetSum().(*OracleStreamMessage_GetPubKeyResponse); ok {
		return x.GetPubKeyResponse
	}
	return nil
}

func (x *OracleStreamMessage) GetPing() *Ping {
	if x, ok := x.GetSum().(*OracleStreamMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *OracleStreamMessage) GetPong() *Pong {
	if x, ok := x.GetSum().(*OracleStreamMessage_Pong); ok {
		return x.Pong
	}
	return nil
}

type isOracleStreamMessage_Sum interface {
	isOracleStreamMessage_Sum()
}

type OracleStreamMessage_SignPriceFeedRequest struct {
	SignPriceFeedRequest *SignPriceFeedRequest `protobuf:"bytes,1,opt,name=sign_price_feed_request,json=signPriceFeedRequest,proto3,oneof"`
}

type OracleStreamMessage_SignPriceFeedResponse struct {
	SignPriceFeedResponse *SignPriceFeedResponse `protobuf:"bytes,2,opt,name=sign_price_feed_response,json=signPriceFeedResponse,proto3,oneof"`
}

type OracleStreamMessage_GetPubKeyRequest struct {
	GetPubKeyRequest *GetPubKeyRequest `protobuf:"bytes,3,opt,name=get_pub_key_request,json=getPubKeyRequest,proto3,oneof"`
}

type OracleStreamMessage_GetPubKeyResponse struct {
	GetPubKeyResponse *GetPubKeyResponse `protobuf:"bytes,4,opt,name=get_pub_key_response,json=getPubKeyResponse,proto3,oneof"`
}

type OracleStreamMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type OracleStreamMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,6,opt,name=pong,proto3,oneof"`
}

func (*OracleStreamMessage_SignPriceFeedRequest) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_SignPriceFeedResponse) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_GetPubKeyRequest) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_GetPubKeyResponse) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_Ping) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_Pong) isOracleStreamMessage_Sum() {}

var File_privval_v1_types_proto protoreflect.FileDescriptor

var file_privval_v1_types_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x22, 0x41, 0x0a, 0x14, 0x53, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x61, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x72, 0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x15, 0x53, 0x69, 0x67, 0x6e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x22, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x51, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x06, 0x0a, 0x04,
	0x50, 0x6f, 0x6e, 0x67, 0x22, 0xc6, 0x03, 0x0a, 0x13, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x59, 0x0a, 0x17,
	0x73, 0x69, 0x67, 0x6e, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x14, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5c, 0x0a, 0x18, 0x73, 0x69, 0x67, 0x6e, 0x5f,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x15,
	0x73, 0x69, 0x67, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x75, 0x62,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x10, 0x67, 0x65, 0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x75, 0x62, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x11, 0x67, 0x65, 0x74, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x26,
	0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48, 0x00,
	0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x75, 0x61,
	0x2d, 0x78, 0x79, 0x7a, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2d, 0x66, 0x65, 0x65, 0x64, 0x65,
	0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x76,
	0x61, 0x6c, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_privval_v1_types_proto_rawDescOnce sync.Once
	file_privval_v1_types_proto_rawDescData = file_privval_v1_types_proto_rawDesc
)

func file_privval_v1_types_proto_rawDescGZIP() []byte {
	file_privval_v1_types_proto_rawDescOnce.Do(func() {
		file_privval_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_privval_v1_types_proto_rawDescData)
	})
	return file_privval_v1_types_proto_rawDescData
}

var file_privval_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_privval_v1_types_proto_goTypes = []any{
	(*SignPriceFeedRequest)(nil),  // 0: privval.v1.SignPriceFeedRequest
	(*SignPriceFeedResponse)(nil), // 1: privval.v1.SignPriceFeedResponse
	(*GetPubKeyRequest)(nil),      // 2: privval.v1.GetPubKeyRequest
	(*GetPubKeyResponse)(nil),     // 3: privval.v1.GetPubKeyResponse
	(*Ping)(nil),                  // 4: privval.v1.Ping
	(*Pong)(nil),                  // 5: privval.v1.Pong
	(*OracleStreamMessage)(nil),   // 6: privval.v1.OracleStreamMessage
}
var file_privval_v1_types_proto_depIdxs = []int32{
	0, // 0: privval.v1.OracleStreamMessage.sign_price_feed_request:type_name -> privval.v1.SignPriceFeedRequest
	1, // 1: privval.v1.OracleStreamMessage.sign_price_feed_response:type_name -> privval.v1.SignPriceFeedResponse
	2, // 2: privval.v1.OracleStreamMessage.get_pub_key_request:type_name -> privval.v1.GetPubKeyRequest
	3, // 3: privval.v1.OracleStreamMessage.get_pub_key_response:type_name -> privval.v1.GetPubKeyResponse
	4, // 4: privval.v1.OracleStreamMessage.ping:type_name -> privval.v1.Ping
	5, // 5: privval.v1.OracleStreamMessage.pong:type_name -> privval.v1.Pong
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_privval_v1_types_proto_init() }
func file_privval_v1_types_proto_init() {
	if File_privval_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_privval_v1_types_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SignPriceFeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SignPriceFeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetPubKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetPubKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*OracleStreamMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_privval_v1_types_proto_msgTypes[6].OneofWrappers = []any{
		(*OracleStreamMessage_SignPriceFeedRequest)(nil),
		(*OracleStreamMessage_SignPriceFeedResponse)(nil),
		(*OracleStreamMessage_GetPubKeyRequest)(nil),
		(*OracleStreamMessage_GetPubKeyResponse)(nil),
		(*OracleStreamMessage_Ping)(nil),
		(*OracleStreamMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_privval_v1_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_privval_v1_types_proto_goTypes,
		DependencyIndexes: file_privval_v1_types_proto_depIdxs,
		MessageInfos:      file_privval_v1_types_proto_msgTypes,
	}.Build()
	File_privval_v1_types_proto = out.File
	file_privval_v1_types_proto_rawDesc = nil
	file_privval_v1_types_proto_goTypes = nil
	file_privval_v1_types_proto_depIdxs = nil
}
